# Generated by Django 6.0.5 on 2026-06-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('produtos', '0001_initial'),
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='estoque_minimo',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('produto', 'unidade')},
        ),
    ]
