# Generated by Django 6.0.5 on 2026-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='consentimento_lgpd',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='role',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENTE', 'Cliente'), ('FUNCIONARIO', 'Funcionario')], default='CLIENTE', max_length=20),
        ),
    ]
